### ISSUE TITLE
Замусоривание системных папок

### ISSUE THREAD

**Issue by JerryImMouse** [poeMota/map-converter-ss14#1]
Уже было хотел поставить потестить, но мне кажется, что срать в аппдату это мега плохая идея. Не лучше ли будет всем, если ты просто зальешь его в корень проекта?
```py
if system == "Windows":
        configDir = os.getenv('APPDATA')
    elif system in ["Linux", "Darwin"]:  # "Darwin" for macOS
        configDir = Path.home() / ".config"
```

**Comment by poeMota** [comment]
Я так изначально и хотел, но мне показалось плохим тоном что если приложение удалить то удалиться и конфиг, но с другой стороны это не какая то серьезная программа, так что можно

**Comment by JerryImMouse** [comment]
> Я так изначально и хотел, но мне показалось плохим тоном что если приложение удалить то удалиться и конфиг, но с другой стороны это не какая то серьезная программа, так что можно

User-issue
